<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJsBnxMf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJsBnxMf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJsBnxMf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJsBnxMf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJsBnxMf\App_KernelDevDebugContainer([
    'container.build_hash' => 'JsBnxMf',
    'container.build_id' => 'd74eb9c0',
    'container.build_time' => 1687070435,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJsBnxMf');
